version: 2
jobs:
  build:
    working_directory: ~/dist
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: npm i --save-dev karma-phantomjs-launcher
      - run: xvfb-run -a npm run test-ci
      - run: xvfb-run -a npm run build