version: 2
jobs:
  build:
    working_directory: ~/dist
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: ng test --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run: xvfb-run -a npm run build